/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: monitor.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "monitor.pb-c.h"
void   system_info__init
                     (SystemInfo         *message)
{
  static const SystemInfo init_value = SYSTEM_INFO__INIT;
  *message = init_value;
}
size_t system_info__get_packed_size
                     (const SystemInfo *message)
{
  assert(message->base.descriptor == &system_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t system_info__pack
                     (const SystemInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &system_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t system_info__pack_to_buffer
                     (const SystemInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &system_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SystemInfo *
       system_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SystemInfo *)
     protobuf_c_message_unpack (&system_info__descriptor,
                                allocator, len, data);
}
void   system_info__free_unpacked
                     (SystemInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &system_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   performance_info__load_avg__init
                     (PerformanceInfo__LoadAvg         *message)
{
  static const PerformanceInfo__LoadAvg init_value = PERFORMANCE_INFO__LOAD_AVG__INIT;
  *message = init_value;
}
void   performance_info__init
                     (PerformanceInfo         *message)
{
  static const PerformanceInfo init_value = PERFORMANCE_INFO__INIT;
  *message = init_value;
}
size_t performance_info__get_packed_size
                     (const PerformanceInfo *message)
{
  assert(message->base.descriptor == &performance_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t performance_info__pack
                     (const PerformanceInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &performance_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t performance_info__pack_to_buffer
                     (const PerformanceInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &performance_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PerformanceInfo *
       performance_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PerformanceInfo *)
     protobuf_c_message_unpack (&performance_info__descriptor,
                                allocator, len, data);
}
void   performance_info__free_unpacked
                     (PerformanceInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &performance_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor system_info__field_descriptors[4] =
{
  {
    "system_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SystemInfo, system_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SystemInfo, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_processors",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SystemInfo, num_processors),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_total",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SystemInfo, mem_total),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned system_info__field_indices_by_name[] = {
  3,   /* field[3] = mem_total */
  2,   /* field[2] = num_processors */
  0,   /* field[0] = system_name */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange system_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor system_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SystemInfo",
  "SystemInfo",
  "SystemInfo",
  "",
  sizeof(SystemInfo),
  4,
  system_info__field_descriptors,
  system_info__field_indices_by_name,
  1,  system_info__number_ranges,
  (ProtobufCMessageInit) system_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor performance_info__load_avg__field_descriptors[3] =
{
  {
    "min5",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(PerformanceInfo__LoadAvg, min5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min10",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(PerformanceInfo__LoadAvg, min10),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min15",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(PerformanceInfo__LoadAvg, min15),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned performance_info__load_avg__field_indices_by_name[] = {
  1,   /* field[1] = min10 */
  2,   /* field[2] = min15 */
  0,   /* field[0] = min5 */
};
static const ProtobufCIntRange performance_info__load_avg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor performance_info__load_avg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PerformanceInfo.LoadAvg",
  "LoadAvg",
  "PerformanceInfo__LoadAvg",
  "",
  sizeof(PerformanceInfo__LoadAvg),
  3,
  performance_info__load_avg__field_descriptors,
  performance_info__load_avg__field_indices_by_name,
  1,  performance_info__load_avg__number_ranges,
  (ProtobufCMessageInit) performance_info__load_avg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor performance_info__field_descriptors[6] =
{
  {
    "uptime",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(PerformanceInfo, uptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "processor_usage",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(PerformanceInfo, n_processor_usage),
    offsetof(PerformanceInfo, processor_usage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mem_free",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PerformanceInfo, mem_free),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_process",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PerformanceInfo, num_process),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_process_running",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PerformanceInfo, num_process_running),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loadavg",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PerformanceInfo, loadavg),
    &performance_info__load_avg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned performance_info__field_indices_by_name[] = {
  5,   /* field[5] = loadavg */
  2,   /* field[2] = mem_free */
  3,   /* field[3] = num_process */
  4,   /* field[4] = num_process_running */
  1,   /* field[1] = processor_usage */
  0,   /* field[0] = uptime */
};
static const ProtobufCIntRange performance_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor performance_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PerformanceInfo",
  "PerformanceInfo",
  "PerformanceInfo",
  "",
  sizeof(PerformanceInfo),
  6,
  performance_info__field_descriptors,
  performance_info__field_indices_by_name,
  1,  performance_info__number_ranges,
  (ProtobufCMessageInit) performance_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
